language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hunspell
  - gem install bundler -v 1.13.5
notifications:
  email: false
  webhooks:
    urls:
      - https://uplink-app.herokuapp.com/travis_hooks
