language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hunspell
  - gem install bundler -v 1.13.5
notifications:
  email: false
  webhooks:
    urls:
      secure: TKpH2LqX/Q8XqLdDDrS5Nz08a9DQjxGjduEsZlk4XN5pcsLCwuugp1KWxHA8S3jCW4fVdWIR07Uac8kUB+RdsTE5OYTr325ZSGtK7uF7xI4ngXM+PhAwTw9nRznDa1rJsW30mOhUL7bBIZS5rOSBR9SFIsFkcHxKHvsjJm3wflAXtt6Qk1PntZiUYTwwNSy4cnqeMOCv0hrZJd2y0tCysQrh3AGI8EZGxU/kI+6DGGb6PLtje5maSPABFpvZ8eKHS5vQt6/f4msnh0fb5X4kFy6Y7rnLsV6AhL+PBdvgq6XUogGXbFqTfjuI3BXHmID6YXIHocHxfqVNu+bFBwFvFWMdMfR4MipLGJLJEPa/ki1SZ3G+6MWHN59Ty1KAygO9QztjlPcfoaitqTZbxgvWu3liOaoCSWl9YAAz7jwO3LRKzuWXwJM0JXmGM+hb7OYROMLfWwhOWcAk+LmKoEAhClsn4TONuN7PoWJpemH/k3rbRCpxuz3nfAIPHulNfAlLgd8kv7g7CxabAAqFJGDS1iN2vd3k2s6HStTAv7RxI1yUppuj9ZB69rWX4t5mvfcvGoQsn6UFxLy4WNsQAfXO9mpJhxqrt62UZD5+BeUm2hi3WQsv/0E6p7NcuGUN0zvD5M+PSwwLVPndartTIKTww+mT2Ra1z+L2+ZVBdSjU3xc=
